Repository pixelsdb/mini-pixels, pull requests merged in 2025-01, with the labels that each got.

#47 [Issue #46] revise writer unit tests
  tests/writer/CMakeLists.txt
  tests/writer/IntegerWriterTest.cpp
  tests/writer/PixelsWriterTest.cpp
Labels: bug

#55 [Issue #54] add missing boost lib dependencies
  pixels-cli/CMakeLists.txt
Labels: bug

#53 [Issue #52] resolve void pointer arithmetic error by adding explicit type casts
  pixels-core/lib/reader/IntegerColumnReader.cpp
Labels: bug, enhancement

#51 [Issue #56] add missing includes for GCC 14 compatibility
  pixels-common/include/physical/Request.h
  pixels-core/include/exception/PixelsFileVersionInvalidException.h
  tests/writer/IntegerWriterTest.cpp
Labels: enhancement

#64 [Issue #20] fix typos in pixels-cli
  experiments/tips.md
  pixels-cli/main.cpp
Labels: enhancement

#65 [Issue #62] fix compilation errors
  pixels-core/lib/writer/ColumnWriter.cpp
  pixels-core/lib/writer/IntegerColumnWriter.cpp
Labels: bug
